# Cura PostProcessingPlugin
# Author:   Eric Dey
# Date:     March 03, 2020
# Modified: March 06, 2020

# Description:  This plugin displayes the time remaining and the layer progress
#               on the LCD using the ;TIME and ;LAYER comments generated by Cura.

from ..Script import Script


class DisplayRemainingTimeAndLayersOnLCD(Script):

    def __init__(self):
        super().__init__()
        
        self.defaultRemainingWord = "Rem... "
        self.defaultCompletionWord = "Done!"
        
        self.displayUpdateFormat = """M117 %s %dh %02dm %dL"""
        self.displayUpdateCloseFormat = """M117 %s %dm %02ds %dL"""
        self.displayCompletedFormat = """M117 %s ET %dh %02dm %02ds"""
    

    def getSettingDataString(self):
        return("""{
            "name":"Display Remaining Time and Layers on LCD",
            "key":"DisplayRemainingTimeAndLayersOnLCD",
            "metadata": {},
            "version": 2,
            "settings":
            {
                "ScriptEnabled":
                {
                    "label": "Enable",
                    "description": "Enable to write time and layers remaining on the display during printing.",
                    "type": "bool",
                    "default_value": false
                },
                "RemainingWord":
                {
                    "label": "Work remaining word",
                    "description": "Word displayed that describes the work remaining. Keep it short (1-6 chars).",
                    "type": "str",
                    "default_value": "%s"
                },
                "CompletionWord":
                {
                    "label": "Job completion word",
                    "description": "Word displayed that describes the end of the job. Keep it short (1-6 chars).",
                    "type": "str",
                    "default_value": "%s"
                },
                "CompletionAlertSeconds":
                {
                    "label": "Completion Alert Duration",
                    "description": "Number of seconds to play job completion alert sound. Set to 0 to disable.",
                    "type": "int",
                    "default_value": 15
                }
            }
        }""" % (self.defaultRemainingWord, self.defaultCompletionWord))
    
    
    def _formatUpdateGcode(self, word, hours, minutes, seconds, layerRem):
        """return a GCode string to display remaining work text"""
        if hours < 0: hours = 0
        if minutes < 0: minutes = 0
        if seconds < 0: seconds = 0
        if layerRem < 0: layerRem = 0
        if hours == 0 and minutes < 10:
            return(self.displayUpdateCloseFormat % (word, minutes, seconds, layerRem))
        return(self.displayUpdateFormat % (word, hours, minutes, layerRem))
    
    
    def _formatCompletedGcode(self, word, hours, minutes, seconds):
        """return a GCode string to display completion and original time estimate"""
        gcode = self.displayCompletedFormat % (word, hours, minutes, seconds)
        gcode += "\nM300 S0 P100"  # 100ms pause to ensure message display
        return(gcode)


    def _playEndSoundGcode(self, seconds):
        """return a GCode string to play the end alert sound sequence"""
        if seconds <= 0:
            return (";Job completion alert sound disabled")
        gcode = ";Play job completion alert for %s seconds" % (seconds)
        
        soundOnDur = 63    # milliseconds
        soundOffDur = 500  # milliseconds
        reps = int((seconds * 1000.0) / (soundOnDur + soundOffDur)) + 1
        for n in range(0, reps):
            gcode += "\nM300 S1000 P%s\nM300 S0 P%s" % (soundOnDur, soundOffDur)
        gcode += "\nM300 S0 P1"  # ensure sound is off
        gcode += "\n;End of job completion alert"
        return(gcode)
        
    
    def execute(self, data):
        if not self.getSettingValueByKey("ScriptEnabled"):
            return(data)
        
        totalTime = None   # total job time in whole seconds
        remainingTime = 0
        totalLayers = len(data)  # estimate of layer count
        remainingWord = self.getSettingValueByKey("RemainingWord")
        completionWord = self.getSettingValueByKey("CompletionWord")
        completionAlertSeconds = self.getSettingValueByKey("CompletionAlertSeconds")
        
        # these are the components of total time
        totalHrs = -1
        totalMin = -1
        totalSec = -1
        totalComponentsInitialized = False
        
        layerNum = 0
        for layer in data:
            lines = layer.split("\n")
            lineNum = 0   # line number within this layer
            
            for line in lines:
                # skip to next line if this isn't a comment
                if not line.startswith(";"):
                    lineNum += 1
                    continue
            
                createNewDisplayLine = False
                if line.startswith(";TIME:"):
                    # Line format with total time: ;TIME:12345
                    createNewDisplayLine = True
                    remainingTime = int(line.split(':')[1])
                    
                    # special case for multiple ;TIME markers
                    if totalTime is not None:
                        elaspedTime = totalTime - remainingTime
                    else:
                        totalTime = remainingTime  # set total time on first ;TIME field
                    
                elif line.startswith(";TIME_ELAPSED:"):
                    # Line format with remaining time: ;TIME_ELAPSED:123.456789
                    createNewDisplayLine = True
                    elaspedTime = int(float(line.split(':')[1]) + 0.5)
                    remainingTime = totalTime - elaspedTime
                    if remainingTime < 0: 
                        remainingTime = 0
                    
                elif line.startswith(";LAYER_COUNT:"):
                    # Reset layer count; line format: ;LAYER_COUNT:123
                    createNewDisplayLine = True
                    totalLayers = int(line.split(':')[1])
                
                # Break out total time into h,m,s components
                if totalComponentsInitialized is False and totalTime is not None:
                    totalComponentsInitialized = True
                    totalMin, totalSec = divmod(totalTime, 60) # total min, 0-59 sec
                    totalHrs, totalMin = divmod(totalMin, 60)  # total hr, 0-59 min
                
                
                # Insert a new GCode line by using a newline in the existing string
                # and update the current line list entry of GCode
                if createNewDisplayLine is True:
                    # Break out remaining time into h,m,s components
                    remMin, remSec = divmod(remainingTime, 60)
                    remHrs, remMin = divmod(remMin, 60)
                    
                    newLine = line
                    newLine = newLine + "\n;Time remaining %d:%02d:%02d" % (remHrs, remMin, remSec)
                    newLine = newLine + "\n%s" % (self._formatUpdateGcode(remainingWord, remHrs, remMin, remSec, totalLayers-layerNum+1))
                    lines[lineNum] = newLine   # replace the line of GCode
                    data[layerNum] = "\n".join(lines)  # replace the layer text
                
                lineNum += 1
            
            layerNum += 1
        
        # add a final display line for job completion
        data.append(self._formatCompletedGcode(completionWord, totalHrs, totalMin, totalSec) + "\n")
        
        # play completion alert sound
        data.append(self._playEndSoundGcode(completionAlertSeconds) + "\n")

        return(data)
